version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: lani_development
      POSTGRES_USER: lani
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
    command: start-dev

  keycloak_db:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://lani:password@db:5432/lani_development
      REDIS_URL: redis://redis:6379/0
      KEYCLOAK_URL: http://keycloak:8080
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    stdin_open: true
    tty: true

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://lani:password@db:5432/lani_development
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle

volumes:
  postgres_data:
  keycloak_data:
  bundle_cache:
