apiVersion: v1
kind: Secret
metadata:
  name: lani-secrets
  namespace: lani-production
  labels:
    app.kubernetes.io/name: lani
    app.kubernetes.io/instance: lani-production
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Rails Configuration
  SECRET_KEY_BASE: "REPLACE_WITH_ACTUAL_SECRET"
  RAILS_MASTER_KEY: "REPLACE_WITH_ACTUAL_MASTER_KEY"
  
  # Database Configuration
  DATABASE_URL: "postgres://postgres:REPLACE_WITH_DB_PASSWORD@lani-postgresql:5432/lani_production"
  POSTGRES_PASSWORD: "REPLACE_WITH_DB_PASSWORD"
  
  # Redis Configuration
  REDIS_URL: "redis://:REPLACE_WITH_REDIS_PASSWORD@lani-redis:6379/0"
  REDIS_PASSWORD: "REPLACE_WITH_REDIS_PASSWORD"
  
  # Stripe Configuration
  STRIPE_SECRET_KEY: "sk_live_REPLACE_WITH_STRIPE_SECRET"
  STRIPE_PUBLISHABLE_KEY: "pk_live_REPLACE_WITH_STRIPE_PUBLISHABLE"
  STRIPE_WEBHOOK_SECRET: "whsec_REPLACE_WITH_WEBHOOK_SECRET"
  
  # External API Keys
  MAPBOX_ACCESS_TOKEN: "pk.eyJ1REPLACE_WITH_MAPBOX_TOKEN"
  OPENPROJECT_API_KEY: "REPLACE_WITH_OPENPROJECT_API_KEY"
  MAYBE_API_KEY: "REPLACE_WITH_MAYBE_API_KEY"
  NEXTCLOUD_USERNAME: "REPLACE_WITH_NEXTCLOUD_USER"
  NEXTCLOUD_PASSWORD: "REPLACE_WITH_NEXTCLOUD_PASSWORD"
  MEDUSA_API_KEY: "REPLACE_WITH_MEDUSA_API_KEY"
  
  # Email Configuration
  SMTP_HOST: "smtp.example.com"
  SMTP_USERNAME: "noreply@lani.dev"
  SMTP_PASSWORD: "REPLACE_WITH_SMTP_PASSWORD"
  
  # Monitoring and Logging
  NEW_RELIC_LICENSE_KEY: "REPLACE_WITH_NEWRELIC_KEY"
  SENTRY_DSN: "https://REPLACE_WITH_SENTRY_DSN"
  DATADOG_API_KEY: "REPLACE_WITH_DATADOG_KEY"
  
  # Storage Configuration
  AWS_ACCESS_KEY_ID: "REPLACE_WITH_AWS_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "REPLACE_WITH_AWS_SECRET_KEY"
  AWS_REGION: "us-east-1"
  AWS_S3_BUCKET: "lani-production-storage"

---
apiVersion: v1
kind: Secret
metadata:
  name: lani-postgresql-secret
  namespace: lani-production
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: lani-production
    app.kubernetes.io/component: database
type: Opaque
stringData:
  postgres-password: "REPLACE_WITH_DB_PASSWORD"
  password: "REPLACE_WITH_DB_PASSWORD"

---
apiVersion: v1
kind: Secret
metadata:
  name: lani-redis-secret
  namespace: lani-production
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: lani-production
    app.kubernetes.io/component: cache
type: Opaque
stringData:
  redis-password: "REPLACE_WITH_REDIS_PASSWORD"

---
# External Secrets Operator configuration (optional)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: lani-secret-store
  namespace: lani-production
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: lani-external-secrets-sa

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lani-external-secrets
  namespace: lani-production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: lani-secret-store
    kind: SecretStore
  target:
    name: lani-secrets
    creationPolicy: Owner
  data:
  - secretKey: SECRET_KEY_BASE
    remoteRef:
      key: lani/production
      property: secret_key_base
  - secretKey: RAILS_MASTER_KEY
    remoteRef:
      key: lani/production
      property: rails_master_key
  - secretKey: DATABASE_URL
    remoteRef:
      key: lani/production
      property: database_url
  - secretKey: REDIS_URL
    remoteRef:
      key: lani/production
      property: redis_url
  - secretKey: STRIPE_SECRET_KEY
    remoteRef:
      key: lani/production
      property: stripe_secret_key
  - secretKey: STRIPE_PUBLISHABLE_KEY
    remoteRef:
      key: lani/production
      property: stripe_publishable_key
  - secretKey: STRIPE_WEBHOOK_SECRET
    remoteRef:
      key: lani/production
      property: stripe_webhook_secret
  - secretKey: MAPBOX_ACCESS_TOKEN
    remoteRef:
      key: lani/production
      property: mapbox_access_token
  - secretKey: OPENPROJECT_API_KEY
    remoteRef:
      key: lani/production
      property: openproject_api_key
  - secretKey: MAYBE_API_KEY
    remoteRef:
      key: lani/production
      property: maybe_api_key
  - secretKey: NEXTCLOUD_USERNAME
    remoteRef:
      key: lani/production
      property: nextcloud_username
  - secretKey: NEXTCLOUD_PASSWORD
    remoteRef:
      key: lani/production
      property: nextcloud_password
  - secretKey: MEDUSA_API_KEY
    remoteRef:
      key: lani/production
      property: medusa_api_key
