{{- if .Values.autoscaling.web.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "lani.fullname" . }}-web-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lani.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lani.fullname" . }}-web
  minReplicas: {{ .Values.autoscaling.web.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.web.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.web.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.web.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.web.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.web.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
{{- end }}

---
{{- if and .Values.sidekiq.enabled .Values.autoscaling.sidekiq.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "lani.fullname" . }}-sidekiq-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lani.labels" . | nindent 4 }}
    app.kubernetes.io/component: sidekiq-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lani.fullname" . }}-sidekiq
  minReplicas: {{ .Values.autoscaling.sidekiq.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.sidekiq.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.sidekiq.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.sidekiq.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.sidekiq.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.sidekiq.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
{{- end }}
