{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "lani.fullname" . }}-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lani.labels" . | nindent 4 }}
    app.kubernetes.io/component: network-policy
spec:
  podSelector:
    matchLabels:
      {{- include "lani.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkPolicy.ingress.enabled }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
    # Allow ingress from nginx ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 3000
    # Allow health checks from within namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: 3000
    # Allow communication between lani components
    - from:
        - podSelector:
            matchLabels:
              {{- include "lani.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 3000
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    # Allow egress to PostgreSQL
    {{- if eq .Values.postgresql.type "internal" }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 5432
    {{- end }}
    # Allow egress to Redis
    {{- if eq .Values.redis.type "internal" }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 6379
    {{- end }}
    # Allow egress to external services (DNS, HTTPS, SMTP)
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 587
        - protocol: TCP
          port: 25
    # Allow communication between lani components
    - to:
        - podSelector:
            matchLabels:
              {{- include "lani.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 3000
  {{- end }}
{{- end }}
