name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm/lani/**'
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.14.0'

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add jetstack https://charts.jetstack.io
          helm repo update

      - name: Lint Helm Chart
        run: |
          helm lint helm/lani/
          helm template lani helm/lani/ --debug --dry-run

      - name: Package Helm Chart
        run: |
          mkdir -p .cr-release-packages
          helm package helm/lani/ --destination .cr-release-packages/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Generate Chart Repository Index
        run: |
          mkdir -p public
          cp .cr-release-packages/*.tgz public/
          helm repo index public/ --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  github-release:
    runs-on: ubuntu-latest
    needs: release
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.14.0'

      - name: Package Helm Chart
        run: |
          helm package helm/lani/

      - name: Upload Chart to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lani-*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
